services:
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: network_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    networks:
      - telco_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    container_name: network_aggregator
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - telco_network

  sim_wroclaw:
    build:
      context: ./bts_simulator
      dockerfile: Dockerfile
    container_name: sim_wroclaw_gNodeB
    ports:
      - "8001:8001"
    environment:
      - SIMULATOR_NAME=WRO_5G_01
      - NODE_TYPE=gNodeB
      - LATITUDE=51.107883
      - LONGITUDE=17.038538
      - MAX_THROUGHPUT=10000
      - AGGREGATOR_URL=http://network_aggregator:8000
    depends_on:
      - aggregator
    networks:
      - telco_network

  sim_krakow:
    build:
      context: ./bts_simulator
      dockerfile: Dockerfile
    container_name: sim_krakow_eNodeB
    ports:
      - "8002:8001"
    environment:
      - SIMULATOR_NAME=KRK_4G_01
      - NODE_TYPE=eNodeB
      - LATITUDE=50.064650
      - LONGITUDE=19.944980
      - MAX_THROUGHPUT=1000
      - AGGREGATOR_URL=http://network_aggregator:8000
      - FAULT_PORT=8002
    depends_on:
      - aggregator
    networks:
      - telco_network

  sim_gdansk:
    build:
      context: ./bts_simulator
      dockerfile: Dockerfile
    container_name: sim_gdansk_gNodeB
    ports:
      - "8003:8001"
    environment:
      - SIMULATOR_NAME=GDN_5G_01
      - NODE_TYPE=gNodeB
      - LATITUDE=54.352024
      - LONGITUDE=18.646638
      - MAX_THROUGHPUT=10000
      - AGGREGATOR_URL=http://network_aggregator:8000
      - FAULT_PORT=8003
    depends_on:
      - aggregator
    networks:
      - telco_network

volumes:
  postgres_data:


networks:
  telco_network:
    driver: bridge
